import {
  AlertTriangle,
  ArchiveRestore,
  Boxes,
  Briefcase,
  Building2,
  CalendarCheck,
  ClipboardCheck,
  CreditCard,
  FileDown,
  FileText,
  KeyRound,
  PackageCheck,
  Pill,
  Plus,
  ReceiptText,
  Settings,
  ShieldCheck,
  Store,
  Truck,
  UserCog,
  Users,
  WalletCards,
} from 'lucide-react'
import type { ModulePageConfig } from '../types/module.types'

export const superAdminModules: ModulePageConfig[] = [
  {
    path: '/compras',
    title: 'Compras',
    description: 'Control de compras, proveedores y recepcion de mercaderia',
    primaryAction: 'Nueva compra',
    searchPlaceholder: 'Buscar proveedor o codigo de compra',
    metrics: [
      { label: 'Compras del mes', value: '84', detail: '12 pendientes', icon: Briefcase, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Monto comprado', value: 'S/ 48,320', detail: 'Todas las sucursales', icon: CreditCard, tone: 'bg-sky-100 text-sky-500' },
      { label: 'Recepcionadas', value: '67', detail: 'Mercaderia ingresada', icon: PackageCheck, tone: 'bg-emerald-100 text-emerald-600' },
    ],
    tableTitle: 'Compras recientes',
    tableDescription: 'Ultimas ordenes registradas en el sistema',
    columns: ['Codigo', 'Proveedor', 'Sucursal', 'Estado', 'Total', 'Fecha'],
    rows: [
      ['CMP-1082', 'Pharma Salud S.A.C.', 'Central', 'Recepcionada', 'S/ 3,250.00', '17/06/2026'],
      ['CMP-1081', 'Distribuidora Medica', 'Norte', 'Pendiente', 'S/ 1,850.00', '17/06/2026'],
      ['CMP-1080', 'Laboratorios Andinos', 'Central', 'Recepcionada', 'S/ 2,450.50', '16/06/2026'],
      ['CMP-1079', 'Importaciones Farma', 'Sur', 'Pendiente', 'S/ 980.00', '16/06/2026'],
    ],
    actionsTitle: 'Acciones de compras',
    actions: [
      { label: 'Registrar compra', description: 'Crear una orden con proveedor y detalle', icon: Plus },
      { label: 'Recepcionar mercaderia', description: 'Ingresar lotes y afectar stock', icon: ArchiveRestore },
      { label: 'Exportar compras', description: 'Descargar reporte filtrado', icon: FileDown },
    ],
  },
  {
    path: '/inventario',
    title: 'Inventario',
    description: 'Stock, lotes, vencimientos y movimientos por sucursal',
    primaryAction: 'Ajustar stock',
    searchPlaceholder: 'Buscar producto, lote o codigo',
    metrics: [
      { label: 'Productos activos', value: '1,284', detail: 'Catalogo disponible', icon: Pill, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Stock bajo', value: '18', detail: 'Requieren reposicion', icon: AlertTriangle, tone: 'bg-orange-100 text-orange-600' },
      { label: 'Por vencer', value: '7', detail: 'Proximos 30 dias', icon: CalendarCheck, tone: 'bg-rose-100 text-rose-600' },
    ],
    tableTitle: 'Stock critico',
    tableDescription: 'Productos que necesitan revision prioritaria',
    columns: ['Producto', 'Sucursal', 'Lote', 'Stock', 'Minimo', 'Estado'],
    rows: [
      ['Paracetamol 500mg', 'Central', 'LT-2034', '8', '20', 'Bajo'],
      ['Amoxicilina 500mg', 'Norte', 'LT-1041', '5', '15', 'Bajo'],
      ['Loratadina 10mg', 'Sur', 'LT-8812', '11', '12', 'Observacion'],
      ['Vitamina C 1000mg', 'Central', 'LT-1180', '4', '10', 'Bajo'],
    ],
    actionsTitle: 'Acciones de inventario',
    actions: [
      { label: 'Ajuste de stock', description: 'Registrar entrada o salida manual', icon: Boxes },
      { label: 'Ver lotes FEFO', description: 'Priorizar productos por vencimiento', icon: ClipboardCheck },
      { label: 'Exportar stock', description: 'Descargar inventario global', icon: FileDown },
    ],
  },
  {
    path: '/productos',
    title: 'Productos',
    description: 'Catalogo de medicamentos y productos farmaceuticos',
    primaryAction: 'Nuevo producto',
    searchPlaceholder: 'Buscar por nombre, principio activo o codigo',
    metrics: [
      { label: 'Total productos', value: '1,284', detail: 'Registrados', icon: Pill, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Con receta', value: '326', detail: 'Requieren validacion', icon: ShieldCheck, tone: 'bg-sky-100 text-sky-500' },
      { label: 'Inactivos', value: '42', detail: 'Fuera de venta', icon: AlertTriangle, tone: 'bg-rose-100 text-rose-600' },
    ],
    tableTitle: 'Productos recientes',
    tableDescription: 'Ultimos productos modificados',
    columns: ['Codigo', 'Producto', 'Laboratorio', 'Receta', 'Stock minimo', 'Estado'],
    rows: [
      ['775001', 'Paracetamol 500mg', 'Medifarma', 'No', '20', 'Activo'],
      ['775002', 'Amoxicilina 500mg', 'Andinos', 'Si', '15', 'Activo'],
      ['775003', 'Omeprazol 20mg', 'BioPharma', 'No', '12', 'Activo'],
      ['775004', 'Clonazepam 2mg', 'NeuroLab', 'Si', '8', 'Controlado'],
    ],
    actionsTitle: 'Acciones de productos',
    actions: [
      { label: 'Crear producto', description: 'Registrar datos comerciales y medicos', icon: Plus },
      { label: 'Actualizar precios', description: 'Definir precio por sucursal', icon: CreditCard },
      { label: 'Control de receta', description: 'Marcar productos sensibles', icon: ShieldCheck },
    ],
  },
  {
    path: '/clientes',
    title: 'Clientes',
    description: 'Gestion de clientes y datos de contacto',
    primaryAction: 'Nuevo cliente',
    searchPlaceholder: 'Buscar cliente por DNI, nombre o telefono',
    metrics: [
      { label: 'Clientes registrados', value: '732', detail: 'Base historica', icon: Users, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Nuevos este mes', value: '58', detail: 'Crecimiento activo', icon: Plus, tone: 'bg-emerald-100 text-emerald-600' },
      { label: 'Ventas asociadas', value: '312', detail: 'Con cliente identificado', icon: ReceiptText, tone: 'bg-sky-100 text-sky-500' },
    ],
    tableTitle: 'Clientes recientes',
    tableDescription: 'Ultimos clientes registrados o actualizados',
    columns: ['DNI', 'Cliente', 'Telefono', 'Correo', 'Estado', 'Registro'],
    rows: [
      ['74859621', 'Juan Perez', '987654321', 'juan@mail.com', 'Activo', '17/06/2026'],
      ['72811452', 'Maria Torres', '956781223', 'maria@mail.com', 'Activo', '16/06/2026'],
      ['70124587', 'Luis Gomez', '912445789', '-', 'Activo', '16/06/2026'],
      ['74321098', 'Ana Martinez', '976125440', 'ana@mail.com', 'Activo', '15/06/2026'],
    ],
    actionsTitle: 'Acciones de clientes',
    actions: [
      { label: 'Registrar cliente', description: 'Crear ficha rapida de atencion', icon: Plus },
      { label: 'Ver historial', description: 'Consultar compras del cliente', icon: FileText },
      { label: 'Exportar clientes', description: 'Descargar base filtrada', icon: FileDown },
    ],
  },
  {
    path: '/proveedores',
    title: 'Proveedores',
    description: 'Gestion de proveedores y compras asociadas',
    primaryAction: 'Nuevo proveedor',
    searchPlaceholder: 'Buscar proveedor por RUC o nombre',
    metrics: [
      { label: 'Proveedores activos', value: '46', detail: 'Con compras recientes', icon: Truck, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Compras asociadas', value: '84', detail: 'Mes actual', icon: Briefcase, tone: 'bg-sky-100 text-sky-500' },
      { label: 'Pendientes', value: '12', detail: 'Ordenes sin recepcionar', icon: AlertTriangle, tone: 'bg-orange-100 text-orange-600' },
    ],
    tableTitle: 'Proveedores principales',
    tableDescription: 'Directorio comercial del sistema',
    columns: ['RUC', 'Proveedor', 'Telefono', 'Correo', 'Estado', 'Ultima compra'],
    rows: [
      ['20123456789', 'Pharma Salud S.A.C.', '014445566', 'ventas@pharmasalud.pe', 'Activo', '17/06/2026'],
      ['20555666777', 'Distribuidora Medica', '016667788', 'contacto@dismed.pe', 'Activo', '17/06/2026'],
      ['20444999888', 'Laboratorios Andinos', '017778899', 'comercial@andinos.pe', 'Activo', '16/06/2026'],
      ['20666111222', 'Importaciones Farma', '015551122', 'info@imfarma.pe', 'Activo', '16/06/2026'],
    ],
    actionsTitle: 'Acciones de proveedores',
    actions: [
      { label: 'Crear proveedor', description: 'Registrar datos comerciales', icon: Plus },
      { label: 'Nueva compra', description: 'Iniciar orden para proveedor', icon: Briefcase },
      { label: 'Exportar directorio', description: 'Descargar lista de proveedores', icon: FileDown },
    ],
  },
  {
    path: '/caja',
    title: 'Caja',
    description: 'Turnos, ingresos, egresos y cierres por sucursal',
    primaryAction: 'Abrir caja',
    searchPlaceholder: 'Buscar movimiento o responsable',
    metrics: [
      { label: 'Cajas abiertas', value: '3', detail: 'Sucursales activas', icon: WalletCards, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Ingresos hoy', value: 'S/ 12,540', detail: 'Ventas y manuales', icon: CreditCard, tone: 'bg-emerald-100 text-emerald-600' },
      { label: 'Egresos hoy', value: 'S/ 420', detail: 'Movimientos manuales', icon: ReceiptText, tone: 'bg-rose-100 text-rose-600' },
    ],
    tableTitle: 'Movimientos recientes',
    tableDescription: 'Ultimos movimientos de caja registrados',
    columns: ['Tipo', 'Sucursal', 'Responsable', 'Monto', 'Descripcion', 'Fecha'],
    rows: [
      ['Ingreso', 'Central', 'Maria Lopez', 'S/ 500.00', 'Venta efectivo', '17/06/2026 10:40'],
      ['Egreso', 'Central', 'Maria Lopez', 'S/ 120.00', 'Compra menor', '17/06/2026 10:20'],
      ['Ingreso', 'Norte', 'Carlos Diaz', 'S/ 1,250.00', 'Venta efectivo', '17/06/2026 09:50'],
      ['Egreso', 'Sur', 'Ana Martinez', 'S/ 80.00', 'Gasto operativo', '17/06/2026 09:30'],
    ],
    actionsTitle: 'Acciones de caja',
    actions: [
      { label: 'Abrir turno', description: 'Registrar saldo inicial', icon: WalletCards },
      { label: 'Cerrar caja', description: 'Calcular saldo esperado', icon: ClipboardCheck },
      { label: 'Exportar caja', description: 'Descargar movimientos', icon: FileDown },
    ],
  },
  {
    path: '/reportes',
    title: 'Reportes',
    description: 'Indicadores y reportes globales para gerencia',
    primaryAction: 'Generar reporte',
    searchPlaceholder: 'Buscar reporte o indicador',
    metrics: [
      { label: 'Reportes disponibles', value: '12', detail: 'Ventas, caja e inventario', icon: Building2, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Exportaciones', value: '28', detail: 'Ultimos 30 dias', icon: FileDown, tone: 'bg-sky-100 text-sky-500' },
      { label: 'Indicadores activos', value: '9', detail: 'Dashboard ejecutivo', icon: ClipboardCheck, tone: 'bg-emerald-100 text-emerald-600' },
    ],
    tableTitle: 'Reportes recientes',
    tableDescription: 'Consultas generadas por administradores',
    columns: ['Reporte', 'Rango', 'Sucursal', 'Formato', 'Usuario', 'Fecha'],
    rows: [
      ['Ventas por fecha', 'Junio 2026', 'Todas', 'PDF', 'Maria Lopez', '17/06/2026'],
      ['Stock bajo', 'Actual', 'Central', 'Excel', 'Maria Lopez', '17/06/2026'],
      ['Caja diaria', '16/06/2026', 'Norte', 'PDF', 'Carlos Diaz', '16/06/2026'],
      ['Productos por vencer', '30 dias', 'Todas', 'Excel', 'Maria Lopez', '16/06/2026'],
    ],
    actionsTitle: 'Acciones de reportes',
    actions: [
      { label: 'Reporte ventas', description: 'Filtrar por fecha y sucursal', icon: FileText },
      { label: 'Reporte inventario', description: 'Stock bajo y vencimientos', icon: Boxes },
      { label: 'Reporte caja', description: 'Ingresos, egresos y cierres', icon: WalletCards },
    ],
  },
  {
    path: '/usuarios',
    title: 'Usuarios',
    description: 'Administracion de usuarios, roles y accesos',
    primaryAction: 'Nuevo usuario',
    searchPlaceholder: 'Buscar usuario, correo o rol',
    metrics: [
      { label: 'Usuarios activos', value: '24', detail: 'En todas las sucursales', icon: Users, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Super admins', value: '2', detail: 'Acceso global', icon: KeyRound, tone: 'bg-sky-100 text-sky-500' },
      { label: 'Operadores', value: '18', detail: 'Ventas y caja', icon: UserCog, tone: 'bg-emerald-100 text-emerald-600' },
    ],
    tableTitle: 'Usuarios del sistema',
    tableDescription: 'Accesos disponibles para operar PharmaFlow',
    columns: ['Usuario', 'Correo', 'Rol', 'Sucursal principal', 'Estado', 'Ultimo acceso'],
    rows: [
      ['Maria Lopez', 'maria@pharmaflow.pe', 'super_admin', 'Todas', 'Activo', '17/06/2026 09:30'],
      ['Carlos Diaz', 'carlos@pharmaflow.pe', 'operador', 'Central', 'Activo', '17/06/2026 08:55'],
      ['Ana Martinez', 'ana@pharmaflow.pe', 'administrador', 'Norte', 'Activo', '16/06/2026 18:20'],
      ['Luis Gomez', 'luis@pharmaflow.pe', 'operador', 'Sur', 'Activo', '16/06/2026 17:40'],
    ],
    actionsTitle: 'Acciones de usuarios',
    actions: [
      { label: 'Crear usuario', description: 'Asignar rol y sucursal', icon: Plus },
      { label: 'Gestionar roles', description: 'Super admin, administrador, operador', icon: KeyRound },
      { label: 'Auditar accesos', description: 'Revisar actividad reciente', icon: ClipboardCheck },
    ],
  },
  {
    path: '/sucursales',
    title: 'Sucursales',
    description: 'Gestion global de sedes y asignacion de usuarios',
    primaryAction: 'Nueva sucursal',
    searchPlaceholder: 'Buscar sucursal por nombre o codigo',
    metrics: [
      { label: 'Sucursales activas', value: '4', detail: 'Operando actualmente', icon: Store, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Ventas globales', value: 'S/ 12,540', detail: 'Dia actual', icon: CreditCard, tone: 'bg-emerald-100 text-emerald-600' },
      { label: 'Usuarios asignados', value: '24', detail: 'Entre todas las sedes', icon: Users, tone: 'bg-sky-100 text-sky-500' },
    ],
    tableTitle: 'Listado de sucursales',
    tableDescription: 'Sedes registradas en la organizacion',
    columns: ['Codigo', 'Sucursal', 'Direccion', 'Telefono', 'Estado', 'Usuarios'],
    rows: [
      ['CENTRAL', 'Sucursal Central', 'Av. Principal 123', '014445566', 'Activa', '12'],
      ['NORTE', 'Sucursal Norte', 'Av. Norte 456', '016667788', 'Activa', '6'],
      ['SUR', 'Sucursal Sur', 'Av. Sur 789', '017778899', 'Activa', '5'],
      ['ESTE', 'Sucursal Este', 'Av. Este 321', '015551122', 'Activa', '1'],
    ],
    actionsTitle: 'Acciones de sucursales',
    actions: [
      { label: 'Crear sucursal', description: 'Registrar datos de nueva sede', icon: Plus },
      { label: 'Asignar usuarios', description: 'Vincular equipo a sucursal', icon: Users },
      { label: 'Ver rendimiento', description: 'Comparar ventas por sede', icon: Building2 },
    ],
  },
  {
    path: '/configuracion',
    title: 'Configuracion',
    description: 'Parametros generales del sistema y seguridad',
    primaryAction: 'Guardar cambios',
    searchPlaceholder: 'Buscar parametro o configuracion',
    metrics: [
      { label: 'Roles activos', value: '3', detail: 'super_admin, administrador, operador', icon: KeyRound, tone: 'bg-purple-100 text-[#AE19C2]' },
      { label: 'Monedas', value: '2', detail: 'PEN y USD', icon: CreditCard, tone: 'bg-sky-100 text-sky-500' },
      { label: 'Alertas', value: '5', detail: 'Reglas configuradas', icon: AlertTriangle, tone: 'bg-orange-100 text-orange-600' },
    ],
    tableTitle: 'Parametros principales',
    tableDescription: 'Configuraciones visibles para Super Admin',
    columns: ['Parametro', 'Valor', 'Modulo', 'Estado', 'Actualizado por', 'Fecha'],
    rows: [
      ['Stock minimo por defecto', '5', 'Inventario', 'Activo', 'Maria Lopez', '17/06/2026'],
      ['Dias alerta vencimiento', '30', 'Inventario', 'Activo', 'Maria Lopez', '17/06/2026'],
      ['Moneda principal', 'PEN', 'Ventas', 'Activo', 'Maria Lopez', '16/06/2026'],
      ['Roles simplificados', '3', 'Usuarios', 'Activo', 'Maria Lopez', '16/06/2026'],
    ],
    actionsTitle: 'Acciones de configuracion',
    actions: [
      { label: 'Roles y permisos', description: 'Definir accesos por rol', icon: KeyRound },
      { label: 'Parametros de stock', description: 'Configurar alertas de inventario', icon: Settings },
      { label: 'Auditoria', description: 'Revisar cambios del sistema', icon: ClipboardCheck },
    ],
  },
]

export function getSuperAdminModule(path: string) {
  return superAdminModules.find((module) => module.path === path)
}
